Create a new file, for example, mongodb_backup.sh, and add the following script:
==================================================================================
#!/bin/bash

# Directory to store backups
backup_dir="/path/to/backup/directory"

# MongoDB connection details
mongo_host="localhost"  # Replace with your MongoDB host
mongo_port="27017"      # Replace with your MongoDB port

# Date format for backup file name (e.g., YYYYMMDD)
date_format=$(date +"%Y%m%d")

# Backup MongoDB at 12:30 AM
if [ $(date +"%H%M") = "0030" ]; then
    backup_file="$backup_dir/mongo_backup_$date_format"
    
    # Run mongodump to create the backup
    mongodump --host $mongo_host --port $mongo_port --out $backup_file

    echo "MongoDB backup created: $backup_file"
fi

# Remove backups older than 5 days
find $backup_dir -type f -name 'mongo_backup_*' -mtime +4 -exec rm {} \;

echo "Old backups older than 5 days have been deleted."
===================================================================================================


Make sure to replace /path/to/backup/directory with the directory path where you want to store your backups, and modify mongo_host and mongo_port variables with your MongoDB connection details if they're different.

After creating the script, you'll need to make it executable:

chmod +x mongodb_backup.sh

crontab -e

30 0 * * * /path/to/mongodb_backup.sh >/dev/null 2>&1

This cron schedule will execute the mongodb_backup.sh script every day at 12:30 AM.

Remember to replace /path/to/mongodb_backup.sh with the actual path where your script is located.





>/dev/null: Redirects the standard output (stdout) of the command to /dev/null, a special device file that discards the output. This means any output (like normal messages or errors) from the script execution will not be saved or displayed anywhere.

2>&1: Redirects the standard error (stderr) to the same place as the standard output (which is /dev/null in this case). This ensures that any error messages or output generated by the script also get discarded and are not displayed or saved.
