 Here's an example of a shell script that can perform MySQL backup, keep backups for 5 days, and delete older backups automatically:

=========================================================================================================
 #!/bin/bash

# MySQL database credentials
DB_USER="your_username"
DB_PASS="your_password"
DB_NAME="your_database_name"

# Backup directory
BACKUP_DIR="/path/to/backup/directory"

# Current date
DATE=$(date +%Y%m%d-%H%M%S)

# Create backup directory if it doesn't exist
mkdir -p $BACKUP_DIR

# Perform MySQL backup
mysqldump -u $DB_USER -p$DB_PASS $DB_NAME > $BACKUP_DIR/$DB_NAME-$DATE.sql

# Remove backups older than 5 days
find $BACKUP_DIR -type f -name "$DB_NAME-*.sql" -mtime +5 -exec rm {} \;
=============================================================================================================

Please replace 'your_username', 'your_password', 'your_database_name', and '/path/to/backup/directory' with your actual MySQL credentials and desired backup directory.

To automate the backup process to run daily at 12:30 AM, you can schedule this script using the cron utility. Open the cron jobs editor by running:


crontab -e


30 0 * * * /bin/bash /path/to/your/script.sh


Replace '/path/to/your/script.sh' with the actual path to your shell script file.



>/dev/null: Redirects the standard output (stdout) of the command to /dev/null, a special device file that discards the output. This means any output (like normal messages or errors) from the script execution will not be saved or displayed anywhere.

2>&1: Redirects the standard error (stderr) to the same place as the standard output (which is /dev/null in this case). This ensures that any error messages or output generated by the script also get discarded and are not displayed or saved.

